plugins:
  optimized_privilege_enabled:
    default: true
  optimized_can_close_topic:
    default: true
  optimized_change_username:
    default: true
  optimized_username_change_period:
    default: 180