plugins:
  optimized_privilege_enabled:
    default: true
  optimized_can_close_topic:
    default: true
  optimized_can_open_topic_closed_by_self:
    client: true
    default: true
  optimized_change_username:
    default: true
  optimized_username_change_period:
    default: 180
  optimized_anonymous_instead_of_destroy:
    default: false
  optimized_keep_topics_when_destroy_user:
    default: false
  optimized_topics_move_to_when_destroy_user:
    type: string
    default: system
  optimized_silenced_can_create_post_in_private_message:
    default: true
  optimized_category_ignore_max_consecutive_replies:
    type: category_list
    default: ""
  optimized_tag_ignore_max_consecutive_replies:
    type: tag_list
    default: ""