plugins:
  optimized_privilege_enabled:
    default: true
  optimized_can_close_topic:
    default: true
  optimized_can_open_topic_closed_by_self:
    client: true
    default: true
  optimized_change_username:
    default: true
  optimized_username_change_period:
    default: 180
  optimized_anonymous_instead_of_destroy:
    default: false